### ISSUE TITLE
Walk users through tabs

### ISSUE THREAD

**Issue by jcvdav** [turfeffect/AppDraft#18]
As stated by @spfitzgerald: In terms of user-friendliness, you might want to tell the user when to move on to the next tab since there's no "next" button.  For example, in the 1st (Intro) tab, one sentence: "When ready to begin, select the Objectives and Indicators tab above".  Then in the 2nd (Objectives and Indicators) tab, "After you've selected the appropriate indicators, click on the Data tab above".  Something like that.  No big deal, just one brief sentence on each tab.

**Comment by jcvdav** [comment]
Perhaps something like this?

Using next and previous buttons?

In the UI
```
actionButton(inputId = "b5.6", label = "Siguiente", icon = icon("arrow-right"), class = "btn2")
```

In the Server

```
observeEvent(input$b5.6, {
    updateNavbarPage(session, "Tabs",
                     selected = "Result"
    )
  })
```

![image](https://cloud.githubusercontent.com/assets/11950459/23098264/9cae7a12-f5fe-11e6-9a5e-14dbc123e320.png)

**Comment by spfitzgerald** [comment]
👍
