### ISSUE TITLE
Broke inverts by adding typo to some site names in bio_fish.csv

### ISSUE THREAD

**Issue by alxsmith** [turfeffect/AppDraft#30]
<img width="1393" alt="screen shot 2017-02-15 at 4 59 55 pm" src="https://cloud.githubusercontent.com/assets/16613534/23002548/38400880-f3a0-11e6-816c-5610e8a77962.png">
<img width="641" alt="screen shot 2017-02-15 at 5 00 00 pm" src="https://cloud.githubusercontent.com/assets/16613534/23002549/384283a8-f3a0-11e6-8407-ebde9a8c07c5.png">

**Comment by jcvdav** [comment]
Just to confirm. This happened when you:

1) Introduced a typo in fish database
2) Loaded that dataset
3) Selected the third objective

Right?

**Comment by jcvdav** [comment]
This was fixed in 22810993ed3e74bf2482a1664b0e44767f093606
